// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// EmailSubscriber is the predicate function for emailsubscriber builders.
type EmailSubscriber func(*sql.Selector)
